### ISSUE TITLE
[enhancement] Prevent scroll on Filter switch

### ISSUE THREAD

**Issue by liambarr** [noxify/gridsome-starter-articles#3]
Would love if page scroll wasn't affected when changing filters in the Resources page.
Is this hard to implement?

I've tried with the following: https://github.com/gridsome/gridsome/issues/356, but wasn't able to get it to work.

(Additionally, it could be nice to have the filter sidebar sticky like on Articles)

**Comment by noxify** [comment]
Hi @liambarr 

thanks for the request.

Do you have an example what you mean exactly?
tbh, I'm not sure if I understood your request correctly.

Thanks!

**Comment by liambarr** [comment]
Howdy @noxify,
See these videos for a better understanding:
Currently, this is what happens when you click a filter:
https://streamable.com/sebdo

It'd be nice if the page wouldn't scroll back to the top:
https://streamable.com/my1eq

Similar to how Ajax filtering might work for example.

Obviously not a major issue at the moment with only a few items, but I'd like to remove pagination and have an ever-growing list of resources on the one page. Then if a user were to add a filter - it wouldn't take them all the way back to the start of the page - rather just remove any not in that filter.

**Comment by liambarr** [comment]
For sticky functionality, I simply changed line 2 of src/layouts/sections/resources/Sidebar.vue from:
```
<div>
```
to:
```
<div class="sidebar position-sticky">
```

**Comment by noxify** [comment]
Hi @liambarr 

thanks for the videos :) 

Since it seems that you have both functionalities implemented, 
could you share also the code for the scroll preventing?

**Comment by liambarr** [comment]
@noxify, I haven't actually worked scroll prevention out (just hacked it in the console with jQuery for the video)

**Comment by noxify** [comment]
hey @liambarr 

i found some time to implement it.

Could you give it a try if the scroll prevent solution is enough for you?

You find the changes in the branch "changes" :)

**Comment by liambarr** [comment]
@noxify this is perfect! Thank you

**Comment by liambarr** [comment]
@noxify this is perfect, thanks!
